# -*- coding: utf-8 -*-
"""Listas y Diccionarios (Python).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AY06zzaSB3tfWozIkRwG4RLN3lpImSwd

#Listas y Diccionarios = tipos de datos complejos

#Datos simples
Cadenas = strings
Enteros = int
Decimales = float
Booleano = true or false

#Datos Complejos
Nos permiten almacenar multiples valores a la vez

#Listas = Arrays

Es una coleccion ordenada de elementos, los cuales puedo modificar, agregar o eliminar

(Manzanas, peras, leche, carne, pollo...)

#Diccionario = Objetos

Es una coleccion de datos desordenada almacenado con clave y valor

Clave  Valor
Paula: 3015495389
Pedro: 3105678998
Carlos: 3156984568
"""

#Lista

frutas = ["Manzana", "Pera", "Naranja"]
print(frutas[1]) #Acceder a un elemento de la lista

frutas[2]="Fresas" #Modificar un elemento de la lista
print(frutas[2])

print(*frutas) #el * es para eliminar lo simbolos del codigo

frutas.append("Melon") #Agregar un elemento a la lista
print(*frutas)

frutas.pop() #Eliminar un elemento de la lista
print(*frutas)

frutas.remove("Pera") #Eliminar un elemento especifico de la lista
print(*frutas)

print(len(frutas)) #Tamaño de la lista

#Diccionario

contactos = {
    "Paula": "3015495389",
    "Pedro": "3105678998",
    "Carlos": "3156984568"
}

print("El contacto de maria es:",contactos["Pedro"]) #Acceder a un elemento del diccionario

contactos["stephany"]="3265894587" #Agregando un nuevo contacto
print(contactos)

del contactos["Carlos"] #Eliminando un contacto
print(contactos)

contactos["Paula"]="3698745698" #Modificar un elemento

print(len(contactos)) #Tamaño del diccionario

"""Actividad lista:

1. crear una lista de tareas al menos 5
2. Modificar una de las tareas
3. Elimina la ultima tarea de la lista
4. Agrega una nueva tarea

Actividad diccionario

1. Crea un diccionario que almecene productos y precios
2. Modifica el precio de uno de los productos
3. Agrega un nuevo producto
4. Elimina un producto
"""

#Lista

tareasDelHogar = ["Barrer", "Trapear", "Lavar Ropa", "Lavar loza", "Ordenar Cuarto"]

tareasDelHogar[2]="Lavar Patio"
print(*tareasDelHogar)

tareasDelHogar.remove("Trapear")
print(*tareasDelHogar)

tareasDelHogar.append("Lavar Licuadora")
print(*tareasDelHogar)

#Diccionario

mercado = {
    "Manzanas": "1000 Pesos",
    "Peras": "1200 Pesos",
    "Naranjas": "800 Pesos",
    "Fresas": "1500 Pesos",
    "Tomate": "2000 Pesos"
  }
print("El precio de las naranjas es:",mercado["Naranjas"])

mercado["Naranjas"]="1250 Pesos"
print(mercado)

mercado["Limones"]="1000 Pesos"
print(mercado)

del mercado["Tomate"]
print(mercado)



contactos = {
    "Pedro": {
        "telefono": ["312-231-3123", 3100232321],
        "correo": "pedro@gmail.com",
        "direccion": {"Calle": "Calle 36a #9n 69", "Barrio": "Bosa", "Ciudad": "Bogota"}
    },
    "Carla": {
        "telefono": ["3258974561", 3158925478],
        "correo": "carlagiralgo@outlook.es",
        "direccion": {"Calle": "65 #6n 87", "Barrio": "Medallo", "Ciudad": "Medellin"}
    },
    "Marinela": {
        "telefono": ["659125749", 658423659],
        "correo": "Marinelagonzales@hotmail.com",
        "direccion": {"Calle": "Avenida 6N #6 98", "Barrio": "San vicente", "Ciudad": "Cali"}
    }
}

print(contactos)

contactos["Tatiana"]={ #AGREGAR UN NUEVO CONTACTO
    "telefono": ["312-231-3123", 3100232321],
    "correo": "Tatiana@gmail.com",
}

print(*contactos)

contactos["Martin"]={
    "telefono": ["312-231-3123", 3100232321],
    "correo": ["martin@gmail.com", "Martin@software.com", "martineducacional@gobernacion.gov.co"],
    "direccion": {"Calle": "Cra Norte #6 15", "Barrio": "Aguacatal", "Ciudad": "Cali"}
}

print(contactos)

print("Los telefonos de Tatiana son: ", contactos["Tatiana"]["telefono"]) #Buscar un elemento especifico del diccionario
print("El segundo telefono de Tatiana es: ", contactos["Tatiana"]["telefono"][1])

print("La Ciudad de Carla es: ", contactos["Carla"]["direccion"]["Ciudad"])
ciudadCarla = contactos["Carla"]["direccion"]["Ciudad"] #Puedo guardarlo en una variable
print("La ciudad de Carla es: ", ciudadCarla)

TelfCarla = contactos["Carla"]["telefono"]
print("Los telefonos de Carla son: ", *TelfCarla) #GUARDE LOS TELEFONOS DE CARLA EN UNA VARIABLE

for telefono in TelfCarla:
  print(telefono)

for i, telefono in enumerate(TelfCarla, start=1): #Enumerate es una funcion que agrefa un contador a cada elemento y "start" le indicamos desde que numero ca a empezar a contar
  print(f"Telefono {i}:", telefono)

martinCorreos = contactos["Martin"]["correo"]
#print("Los correos de Martin son: ", *martinCorreos)

for i, correo in enumerate(martinCorreos, start=1):
  print(f"Correo {i}:", correo)

contactos["Marinela"]["Cumpleaños"]="15 de Septiembre" #Agregar una nueva clave al usuario
print(contactos["Marinela"])

contactos["Marinela"]["Fecha de nacimiento"]=[4, "Diciembre", 2008]
print("La fecha de nacimiento de Marinela es: ", *contactos["Marinela"]["Fecha de nacimiento"])

yearNacimiento=contactos["Marinela"]["Fecha de nacimiento"][2]
print("El año de nacimiento de Marinela es: ", yearNacimiento)

yearNacimiento= 2024-yearNacimiento

if yearNacimiento >= 18:
    print("Es mayor de edad")
else:
    print("Es menor de edad")

del contactos["Pedro"] #Borrar un contacto
print(*contactos)

contactos["Martin"]["correo"].remove("Martin@software.com")
print(*contactos["Martin"]["correo"])

colores = ["Rojo", "Verde", "Azul", "Amarillo"]

# Imprimir cada color junto con su posición
for indice, color in enumerate(colores):
    print(f"Color {color} en posición {indice}")

# Modificar el primer color a "Naranja"
colores[0] = "Naranja"

# Eliminar el último color
colores.pop()

# Mostrar la lista final
print("Lista de colores actualizada:", colores)

